version: '3.7'
services:
  app:
    container_name: bugpack-api
    restart: always
    build: .
    environment:
      DB_IP: ${DB_CONTAINER_IP}
    ports:
      - '${PORT}:${PORT}'
    links:
      - mongo
  mongo:
    container_name: bugpack-db
    image: mongo
    ports:
      - '${DB_PORT}:${DB_PORT}'
